import { LegalShell } from "@/components/legal-shell";
import { CONTACT_EMAIL } from "@/lib/constants";

export const metadata = { title: "Privacy" };

export default function PrivacyPage() {
  return <LegalShell eyebrow="Your data" title="Privacy should feel unsurprising." updated="August 5, 2026">
    <section><h2>The short version</h2><p>Fourteen is built to help University of Michigan students express interest without exposing someone’s identity before they consent. We collect only what the launch needs, do not sell personal information, do not use third-party advertising trackers, and do not upload or inspect your phone contacts.</p></section>
    <section><h2>What we collect</h2><ul><li>Account data: school email, first and last name, class year, a generated member number, and confirmation that you are 18 or older.</li><li>Phone data for the manual launch: your mobile number and the time you consented to essential account texts.</li><li>App activity: circle choices, crush actions, chosen message templates, true hint data, guesses, blocks, reports, notification status, and first-party product events.</li><li>Technical data: sign-in session records, timestamps, and ordinary server error logs needed for security and reliability.</li></ul><p>We ask for your date of birth once to check eligibility. We store only the resulting over-18 confirmation, never the birth date itself.</p></section>
    <section><h2>Manual launch operations</h2><p>At launch, essential crush notifications may be sent manually. A restricted founder console can show the intended recipient’s member number, name, phone number, notification text, and an internal sender audit reference. Sender identity is never included in the text sent to the recipient. This is a limited operational exception to the original no-phone prototype brief.</p><p>Access is protected by a separate founder credential, server-only storage, and an audit log for exports and status changes. Before a public launch, hosted data should use encrypted transport, managed database encryption, least-privilege access, key rotation, backups, and a written incident response process.</p></section>
    <section><h2>Who can see what</h2><p>Other students can see your searchable name and class year when allowed by block rules. A crush recipient cannot see the sender’s identity unless the crush becomes mutual or the sender consents after a correct guess. Poll recipients never see who picked them. Founder operations should not browse individual relationships except where strictly necessary to send, troubleshoot, investigate abuse, or meet a legal obligation.</p></section>
    <section><h2>Texts and future automation</h2><p>By opting in during onboarding, you agree to receive essential account texts during the manual launch. Message and data rates may apply. Reply STOP or contact us to opt out. Promotional messages require separate consent. If an automated or AI-operated phone number replaces manual sending, we will keep the same minimum-data message boundary, update this notice, and identify automated interactions where required.</p></section>
    <section><h2>Retention and deletion</h2><p>We keep account data while your account is active and retain limited security or legal records only as necessary. Using Delete account removes your profile, phone number, sessions, circle, crush data, and associated activity from the active system. Backups may take a limited period to expire. Reports may be retained where necessary for safety or legal compliance.</p></section>
    <section><h2>Your choices</h2><p>You can block people, opt out of texts, request access or correction, and delete your account. For privacy requests, email <a href={`mailto:${CONTACT_EMAIL}`}>{CONTACT_EMAIL}</a>. This draft must be reviewed by qualified counsel before public launch.</p></section>
  </LegalShell>;
}
